# Generated by Django 2.2.4 on 2022-07-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20220629_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32)),
                ('file_name', models.CharField(max_length=500)),
            ],
        ),
    ]
