# Generated by Django 2.2.4 on 2022-07-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videos',
        ),
    ]
